---
- meta: end_play
  when: (ansible_distribution != "CentOS" and ansible_distribution_major_version != "7")

- name: Install ELrepo
  yum:
    name: "https://www.elrepo.org/elrepo-release-7.0-4.el7.elrepo.noarch.rpm"
    state: present

- name: Install drbd
  yum:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - kmod-drbd90
    - drbd90-utils

- name: Loading DRBD Kernel Module
  modprobe:
    name: drbd
    state: present

- name: Disable DRBD in systemd
  systemd:
    name: drbd.service
    state: stopped
    enabled: no

- name: Provision DRBD config
  template:
    backup: true
    owner: root
    group: root
    mode: '0744'
    src: "drbd_config.j2"
    dest: "/etc/drbd.d/drbd.res"

- name: Set drbd_t to permissive
  selinux_permissive:
    name: drbd_t
    permissive: true

- name: Configuring firewall ports
  firewalld:
    port: "{{ item }}"
    permanent: yes
    state: enabled
    immediate: yes
  with_items:
    - "7788/tcp"

- name: Check for replay (/opt/drbd_node_done exists)
  stat:
    path: /opt/drbd_node_done
  register: drbd_node_done

- name: Create DRBD device
  command: "drbdadm create-md {{ item.resource }} --force"
  when:
    - drbd_node_done.stat.exists != True
  loop: "{{ drbd }}"

- name: Up DRBD device
  command: "drbdadm up {{ item.resource }}"
  when:
    - drbd_node_done.stat.exists != True
  loop: "{{ drbd }}"

- name: Set DRBD Primary node
  command: "drbdadm primary {{ item.resource }} --force"
  when:
    - drbd_node_done.stat.exists != True
  loop: "{{ drbd }}"
  run_once: True

- name: "Create xfs on device"
  filesystem:
    fstype: xfs
    dev: "{{ item.device }}"
    force: yes
  loop: "{{ drbd }}"
  run_once: True
  ignore_errors: true

- name: Set replay protection (/opt/drbd_node_done)
  file:
    path: /opt/drbd_node_done
    state: touch
    owner: root
    group: root
    mode: '0744'
  when:
    - drbd_node_done.stat.exists != True

- name: Create mountpoint
  file:
    path: "{{ item.mountpoint }}"
    owner: root
    group: root
    mode: '0757'
    state: directory
  loop: "{{ drbd }}"

- name: Allow mountpoint to be public
  sefcontext:
    target: "{{ item.mountpoint }}(/.*)?"
    setype: public_content_rw_t
    state: present
  loop: "{{ drbd }}"

- name: Apply new SELinux file context to mountpoint
  command: "restorecon {{ item.mountpoint }}"
  loop: "{{ drbd }}"
...